package com.youdo.karma.entity;


import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;

/**
 * Dynamic generated by hbm2java
 */
@Entity
public class Dynamic implements java.io.Serializable {
	public static final long serialVersionUID = 1L;

	@Id(autoincrement = true)
	public Long id;
	@Property
	public String nickName;
	@Property
	public String faceUrl;
	@Property
	public String createTime;
	@Property
	public String content;
	@Property
	public boolean isDelete;
	@Property
	public String videos;
	@Property
	public String pictures;
	@Generated(hash = 373190480)
	public Dynamic(Long id, String nickName, String faceUrl, String createTime,
			String content, boolean isDelete, String videos, String pictures) {
		this.id = id;
		this.nickName = nickName;
		this.faceUrl = faceUrl;
		this.createTime = createTime;
		this.content = content;
		this.isDelete = isDelete;
		this.videos = videos;
		this.pictures = pictures;
	}
	@Generated(hash = 316744806)
	public Dynamic() {
	}
	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getCreateTime() {
		return this.createTime;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
	public String getContent() {
		return this.content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public boolean getIsDelete() {
		return this.isDelete;
	}
	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}
	public String getVideos() {
		return this.videos;
	}
	public void setVideos(String videos) {
		this.videos = videos;
	}
	public String getPictures() {
		return this.pictures;
	}
	public void setPictures(String pictures) {
		this.pictures = pictures;
	}
	public String getNickName() {
		return this.nickName;
	}
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	public String getFaceUrl() {
		return this.faceUrl;
	}
	public void setFaceUrl(String faceUrl) {
		this.faceUrl = faceUrl;
	}

}
