package com.youdo.karma.entity;

// Generated 2016-2-12 19:55:00 by Hibernate Tools 3.4.0.CR1

/**
 * Follow generated by hbm2java
 */
public class IdentifyCard implements java.io.Serializable {

	public Integer id;
	public String uid;
	public String nickName;
	public String userName;//名字
	public String idNo;//身份证号
	public String idImgUrl; //身份证图片地址
	public Boolean isIdentify;
}
