package com.youdo.karma.entity;

// Generated 2016-2-12 19:55:00 by Hibernate Tools 3.4.0.CR1

/**
 * Follow generated by hbm2java
 */
public class VideoModel implements java.io.Serializable {

	public Integer id;
	public String usersByUserId;
	public String originalImgPath;
	public String originalVideoPath;
	public String curImgPath;
	public String curVideoPath;
	public String description;
	public String view;
	public String gold;
	public String username;
	public String sex;
	public String type;
	public String isTurnOnVideo;

}
