package com.youdo.karma.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.youdo.karma.entity.ExpressionGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXPRESSION_GROUP".
*/
public class ExpressionGroupDao extends AbstractDao<ExpressionGroup, Long> {

    public static final String TABLENAME = "EXPRESSION_GROUP";

    /**
     * Properties of entity ExpressionGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cover = new Property(1, String.class, "cover", false, "COVER");
        public final static Property Id_pic_themes = new Property(2, int.class, "id_pic_themes", false, "ID_PIC_THEMES");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Zip = new Property(4, String.class, "zip", false, "ZIP");
    }


    public ExpressionGroupDao(DaoConfig config) {
        super(config);
    }
    
    public ExpressionGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXPRESSION_GROUP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COVER\" TEXT NOT NULL ," + // 1: cover
                "\"ID_PIC_THEMES\" INTEGER NOT NULL ," + // 2: id_pic_themes
                "\"NAME\" TEXT NOT NULL ," + // 3: name
                "\"ZIP\" TEXT NOT NULL );"); // 4: zip
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXPRESSION_GROUP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExpressionGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCover());
        stmt.bindLong(3, entity.getId_pic_themes());
        stmt.bindString(4, entity.getName());
        stmt.bindString(5, entity.getZip());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExpressionGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCover());
        stmt.bindLong(3, entity.getId_pic_themes());
        stmt.bindString(4, entity.getName());
        stmt.bindString(5, entity.getZip());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExpressionGroup readEntity(Cursor cursor, int offset) {
        ExpressionGroup entity = new ExpressionGroup( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // cover
            cursor.getInt(offset + 2), // id_pic_themes
            cursor.getString(offset + 3), // name
            cursor.getString(offset + 4) // zip
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExpressionGroup entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCover(cursor.getString(offset + 1));
        entity.setId_pic_themes(cursor.getInt(offset + 2));
        entity.setName(cursor.getString(offset + 3));
        entity.setZip(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExpressionGroup entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExpressionGroup entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExpressionGroup entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
