package com.youdo.karma.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.youdo.karma.entity.FConversation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FCONVERSATION".
*/
public class FConversationDao extends AbstractDao<FConversation, Long> {

    public static final String TABLENAME = "FCONVERSATION";

    /**
     * Properties of entity FConversation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Rid = new Property(1, long.class, "Rid", false, "RID");
        public final static Property Talker = new Property(2, String.class, "talker", false, "TALKER");
        public final static Property TalkerName = new Property(3, String.class, "talkerName", false, "TALKER_NAME");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property UnreadCount = new Property(5, int.class, "unreadCount", false, "UNREAD_COUNT");
        public final static Property CreateTime = new Property(6, long.class, "createTime", false, "CREATE_TIME");
        public final static Property Type = new Property(7, int.class, "type", false, "TYPE");
        public final static Property LocalPortrait = new Property(8, String.class, "localPortrait", false, "LOCAL_PORTRAIT");
        public final static Property FaceUrl = new Property(9, String.class, "faceUrl", false, "FACE_URL");
    }


    public FConversationDao(DaoConfig config) {
        super(config);
    }
    
    public FConversationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FCONVERSATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RID\" INTEGER NOT NULL ," + // 1: Rid
                "\"TALKER\" TEXT NOT NULL UNIQUE ," + // 2: talker
                "\"TALKER_NAME\" TEXT NOT NULL ," + // 3: talkerName
                "\"CONTENT\" TEXT NOT NULL ," + // 4: content
                "\"UNREAD_COUNT\" INTEGER NOT NULL ," + // 5: unreadCount
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 6: createTime
                "\"TYPE\" INTEGER NOT NULL ," + // 7: type
                "\"LOCAL_PORTRAIT\" TEXT," + // 8: localPortrait
                "\"FACE_URL\" TEXT);"); // 9: faceUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FCONVERSATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FConversation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRid());
        stmt.bindString(3, entity.getTalker());
        stmt.bindString(4, entity.getTalkerName());
        stmt.bindString(5, entity.getContent());
        stmt.bindLong(6, entity.getUnreadCount());
        stmt.bindLong(7, entity.getCreateTime());
        stmt.bindLong(8, entity.getType());
 
        String localPortrait = entity.getLocalPortrait();
        if (localPortrait != null) {
            stmt.bindString(9, localPortrait);
        }
 
        String faceUrl = entity.getFaceUrl();
        if (faceUrl != null) {
            stmt.bindString(10, faceUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FConversation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRid());
        stmt.bindString(3, entity.getTalker());
        stmt.bindString(4, entity.getTalkerName());
        stmt.bindString(5, entity.getContent());
        stmt.bindLong(6, entity.getUnreadCount());
        stmt.bindLong(7, entity.getCreateTime());
        stmt.bindLong(8, entity.getType());
 
        String localPortrait = entity.getLocalPortrait();
        if (localPortrait != null) {
            stmt.bindString(9, localPortrait);
        }
 
        String faceUrl = entity.getFaceUrl();
        if (faceUrl != null) {
            stmt.bindString(10, faceUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FConversation readEntity(Cursor cursor, int offset) {
        FConversation entity = new FConversation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // Rid
            cursor.getString(offset + 2), // talker
            cursor.getString(offset + 3), // talkerName
            cursor.getString(offset + 4), // content
            cursor.getInt(offset + 5), // unreadCount
            cursor.getLong(offset + 6), // createTime
            cursor.getInt(offset + 7), // type
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // localPortrait
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // faceUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FConversation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRid(cursor.getLong(offset + 1));
        entity.setTalker(cursor.getString(offset + 2));
        entity.setTalkerName(cursor.getString(offset + 3));
        entity.setContent(cursor.getString(offset + 4));
        entity.setUnreadCount(cursor.getInt(offset + 5));
        entity.setCreateTime(cursor.getLong(offset + 6));
        entity.setType(cursor.getInt(offset + 7));
        entity.setLocalPortrait(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFaceUrl(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FConversation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FConversation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FConversation entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
